# from .utils import ensure_iterable as ensure_iterable
# from _typeshed import Incomplete

# from typing import Any
# def __getattr__(name: str) -> Any: ...

# class Events:
#    items: Incomplete
#    def __init__(self) -> None: ...
#    def __iter__(self): ...
#    def add(self, events): ...
#    def match(self, event: str): ...
