# from .utils import qualname as qualname
# from _typeshed import Incomplete

# from typing import Any
# def __getattr__(name: str) -> Any: ...

# def register(cls): ...
# def get_machine_cls(name): ...
# def init_registry() -> None: ...
# def load_modules(modules: Incomplete | None = None) -> None: ...
