from inspect import BoundArguments, Signature
from typing import Any, Callable

def signature_cache(user_function): ...

class SignatureAdapter(Signature):
    @classmethod
    def wrap(cls, method) -> Callable: ...
    @classmethod
    def from_callable(cls, method): ...
    def bind_expected(self, *args: Any, **kwargs: Any) -> BoundArguments: ...
